var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?6813bffe64d491f8968f13039b0eb611";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
document.writeln("    <div class=\'am-topbar\'>");
document.writeln("        <div class=\'am-g am-g-fixed\'>");
document.writeln("            <div class=\'left\'>");
document.writeln("                <a href=\'index.html\'>");
document.writeln("                    <div class=\'logo\'></div>");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("            <div class=\'right\'>");
document.writeln("                <ul class=\'am-nav am-nav-pills\'>");
document.writeln("                    <li><a href=\'index.html\'>主页</a></li>");
document.writeln("                    <li><a href=\'research.html\'>聚牛猛料</a></li>");
document.writeln("                    <li><a href=\'videos.html\'>今日视点</a></li>");
document.writeln("                    <li><a href=\'product.html\'>会员专享</a></li>");
document.writeln("                    <li><a href=\'theory.html\'>实战擒牛</a></li>");
document.writeln("                    <li><a href=\'team.html\'>团队</a></li>");
document.writeln("                    <li><a href=\'contact.html\'>联系我们</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
$("script[src='js/header.js']").remove();